const data = {
  products: [
    {
      name: "Nike Slim shirt",
      slug: "Nike-slim-shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "hign quality shorts",
    },
    {
      name: "Adidas Fit shirt",
      slug: "Adidas-fit-shirt",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 250,
      countInStock: 20,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 10,
      description: "hign quality product",
    },
    {
      name: "Nike Slim Pant",
      slug: "Nike-slim-pant",
      category: "Pants",
      image: "/images/p3.jpg",
      price: 25,
      countInStock: 15,
      brand: "Nike",
      rating: 4.5,
      numReviews: 14,
      description: "hign quality product",
    },
    {
      name: "Adidas Fit pant",
      slug: "Adidas-fit-pant",
      category: "Pants",
      image: "/images/p4.jpg",
      price: 65,
      countInStock: 5,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 10,
      description: "hign quality product",
    },
  ],
};


export default data;